# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor.proto',
  package='antikeimena',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmotor.proto\x12\x0b\x61ntikeimena\"0\n\x05Motor\x12\x12\n\nspeed_left\x18\x01 \x01(\r\x12\x13\n\x0bspeed_right\x18\x02 \x01(\rb\x06proto3')
)




_MOTOR = _descriptor.Descriptor(
  name='Motor',
  full_name='antikeimena.Motor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed_left', full_name='antikeimena.Motor.speed_left', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed_right', full_name='antikeimena.Motor.speed_right', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Motor'] = _MOTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Motor = _reflection.GeneratedProtocolMessageType('Motor', (_message.Message,), dict(
  DESCRIPTOR = _MOTOR,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:antikeimena.Motor)
  ))
_sym_db.RegisterMessage(Motor)


# @@protoc_insertion_point(module_scope)
